apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    app: frontend
spec:
  containers:
  - name: frontend-env
    image: "IMAGE_REGISTRY"/frontend-env
    ports:
    - containerPort : 8080
    envFrom:
      - configMapRef:
          name: test
    lifecycle:
      postStart:
        exec:
          command: ["/bin/sh", "-c", "envsubst < /usr/share/nginx/html/env_token.js > /usr/share/nginx/html/env.js"]